language: c

os:
  - osx

compiler:
  - gcc

install:
  
  - wget https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz
  - tar xvzf Python-2.7.11.tgz
  - cd Python-2.7.11
  - ./configure MACOSX_DEPLOYMENT_TARGET=10.6 CFLAGS="-arch i386" LDFLAGS="-arch i386" --prefix=$HOME/python_32bit
  - make
  - make install
  - export PATH=$HOME/python_32bit/bin:$PATH
  
  - wget https://pypi.python.org/packages/source/s/setuptools/setuptools-19.1.tar.gz
  - tar xvzf setuptools-19.1.tar.gz
  - cd setuptools-19.1
  - python setup.py install
  - easy_install pip
  - pip install numpy Cython jinja2
  - pip install astropy

script:
  
  - which python
  - python -c 'import sys; print(sys.maxint)'
  - which pip
  - python -c 'import astropy; astropy.test()'